#!/user/bin/perl -w
use strict;

##
#   Author: Chris M.
#   Date: 2 / 19 / 2018
#   Topic: Bioinformatic
#
#   Example: Transcribing DNA to RNA
##

#Actual DNA
my $DNA = "CGGGAGGACGGGAAAATTACTACGGCATTAGC";

#Basic Solution
#'T' to 'U'
my $RNA = $DNA;
$RNA =~ s/T/U/g;

#Best Solution
#'T' to 'U'
(my $RNAs = $DNA) =~ s/T/U/g;

printf("DNA: %s\n" , $DNA);
printf("RNA: %s\n" , $RNAs);
